spin_manifest_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "dioxus-demo"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "dioxus-demo"
source = "target/wasm32-wasi/release/dioxus_demo.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
